### ISSUE TITLE
Errror cant select version

### ISSUE THREAD

**Issue by udgauwdghuadha** [Auties00/Reboot-Launcher#184]
the error code is :
HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:920)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049)
<asynchronous suspension>
![Bild_2024-12-18_082224533](https://github.com/user-attachments/assets/df08e828-9bf3-41cd-b617-f7e40e6ebbd3)
 PLEASE FIX THE ISSUE

**Comment by Auties00** [comment]
Saw someone else with this issue, I’ll see what I can do, but it could be a bug in boring ssl

**Comment by Auties00** [comment]
Fixed in 10.0.6
